version: '3.1'

services:
  oracle:
    image: sath89/oracle-12c
    container_name: oracle
    restart: always
    volumes:
      - ./oracle-data:/u01/app/oracle  # 持久化Oracle数据和配置文件
    ports:
      - some_port:some_port  # Replace with your actual port mapping

  oracledb_exporter:
    image: ghcr.io/iamseth/oracledb_exporter:0.5.0
    container_name: oracledb_exporter
    restart: always
    ports:
      - 9161:9161
    environment:
      - DATA_SOURCE_NAME=oracle://system:oracle@192.168.100.10:1521/xe